Character select screen highlighting using keyboard
miishin/miipd pull request #32
Opened 2021-01-13 02:57 UTC by miishin

Added a highlighting cursor. 

Still need to fix:

- Pressing spacebar adds units to the queue correctly, but does not toggle the actual button on/off, which is weird because I call the same function that is called when clicking with a mouse (which works). 
- The cursor disappears under tiles that have been clicked (toggled on), which also makes no sense because the highlight sprite is on a higher layer.

2021-01-13 14:56 UTC, IsaacPD requested changes

2021-01-13 14:56 UTC, IsaacPD commented on assets/scripts/ability.gd
> -var accuracy : int
Please rebase onto main, or remove this commit that removes accuracy since we already have these changes on main

2021-01-14 00:08 UTC, miishin commented on assets/scripts/character_select.gd
> +	button_grid = [all_buttons.slice(0, 4), all_buttons.slice(5, 9), [$back, $forward]]
latest push fixed it. I forgot to bind back/forward in the keyboard selection lol

2021-01-14 00:09 UTC, miishin commented on debug.log
> +[0112/213931.920:ERROR:settings.cc(325)] Settings version is not 1
no idea

2021-01-18 15:47 UTC, IsaacPD commented on debug.log
> +[0112/213931.920:ERROR:settings.cc(325)] Settings version is not 1
can you just delete this file please -_-

2021-01-18 18:12 UTC, miishin commented on debug.log
> +[0112/213931.920:ERROR:settings.cc(325)] Settings version is not 1
deleted >:)

2021-01-18 18:29 UTC, IsaacPD approved these changes

2021-01-18 18:29 UTC, merged